name: Docker Image CI

on:
  push:
    branches: [ "develop", "master" ]
    tags:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download SoPlanning sources
      run: make download-sources
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Build and push
      id: gen_tags
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["user/image:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: tlancemot/soplanning:${{ fromJson(steps.gen_tags.outputs.tags) }}