name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download SoPlanning sources
      run: make download-sources
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag soplanning:dev-$(date +%s)
